# Generated by Django 3.1.1 on 2021-11-13 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stabile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_manager', models.CharField(max_length=64)),
                ('nome_stabile', models.CharField(max_length=64)),
                ('indirizzo', models.CharField(max_length=64)),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'stabili',
            },
        ),
        migrations.CreateModel(
            name='scena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scena', models.CharField(max_length=64)),
                ('tipo_di_impianto', models.CharField(max_length=64)),
                ('stabile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalAR.stabile')),
            ],
            options={
                'verbose_name_plural': 'scene',
            },
        ),
        migrations.CreateModel(
            name='manutenzione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=64)),
                ('manutentore', models.CharField(max_length=64)),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True)),
                ('è_richiesta_iniziale', models.BooleanField()),
                ('scena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalAR.scena')),
            ],
            options={
                'verbose_name_plural': 'manutenzioni',
            },
        ),
        migrations.CreateModel(
            name='componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modello', models.CharField(max_length=64)),
                ('tipo_di_componente', models.CharField(max_length=64)),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=64)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalAR.scena')),
            ],
            options={
                'verbose_name_plural': 'componenti',
            },
        ),
    ]
