# Generated by Django 3.1.1 on 2021-11-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalAR', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente',
            old_name='tipo_di_componente',
            new_name='codice',
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='origin',
            new_name='scena',
        ),
    ]
